In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv("/content/global_air_quality_datacleaning.csv")

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36437 entries, 0 to 36436
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      36392 non-null  object
 1   City                         36391 non-null  object
 2   Year                         36437 non-null  int64
 3   AQI                          36332 non-null  object
 4   PM2.5                        36358 non-null  object
 5   PM10                         36342 non-null  object
 6   Deforestation_Rate_%         36341 non-null  object
 7   Afforestation_Rate_%         36355 non-null  object
 8   Vehicles_Increase_%          36350 non-null  object
 9   Industries_Increase_%        36349 non-null  object
 10  Env_Budget_Million_USD       36360 non-null  object
 11  Population_Density_Per_SqKm  36348 non-null  object
 12  CO2_Emissions_MT             36348 non-null  object
 13  Green_Space_Ratio_%          36359 non-null  object
 14  Avg_Life_Expectancy_Index    36352 non-null  object
dtypes: int64(1), object(14)
memory usage: 4.2+ MB

In [ ]:
df['Country'] = df['Country'].str.strip().str.lower()

In [ ]:
df['Country'].replace(['-', '?', 'missing', 'unknown'], np.nan, inplace=True)

/tmp/ipykernel_11635/1754987444.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].replace(['-', '?', 'missing', 'unknown'], np.nan, inplace=True)

In [ ]:
df['Country'].unique()

array(['turkey', 'vietnam', 'philippines', 'saudi arabia', 'ethiopia',
       'japan', 'pakistan', 'thailand', 'mongolia', 'iran', 'spain',
       'australia', 'brazil', 'mexico', 'romania', 'indonesia',
       'colombia', 'south africa', 'uae', 'norway', 'tanzania', 'myanmar',
       'russia', 'germany', 'ghana', 'china', 'canada', 'egypt', 'poland',
       'india', 'france', 'argentina', 'morocco', 'sweden', 'nigeria',
       'ukraine', 'uk', 'bangladesh', 'peru', 'usa', 'italy', 'iraq',
       'kenya', 'netherlands', 'chile', 'sout hafrica', 'nigeira', nan,
       'iarn', 'sapin', 'ngieria', 'cihna', 'colmobia', 'vietanm',
       'tahiland', 'agrentina', 'candaa', 'argentnia', 'ukx', 'norawy',
       'inida', 'mongloia', 'mxeico', 'fracne', 'tanzaina', 'bnagladesh',
       'sauid arabia', 'gremany', 'uaex', 'braizl', 'usax', 'eygpt'],
      dtype=object)

In [ ]:
df['Country'].replace({
    'inda': 'india',
    'chnia': 'china',
    'inida': 'india',
    'cihna': 'china',
    'nigeira': 'nigeria',
    'sout hafrica': 'south africa',
    'iarn': 'iran',
    'sapin': 'spain',
    'colmobia': 'colombia',
    'vietanm': 'vietnam',
    'tahiland': 'thailand',
    'agrentina': 'argentina',
    'argentnia': 'argentina',
    'candaa': 'canada',
    'ukx': 'uk',
    'norawy': 'norway',
    'mongloia': 'mongolia',
    'mxeico': 'mexico',
    'fracne': 'france',
    'tanzaina': 'tanzania',
    'bnagladesh': 'bangladesh',
    'sauid arabia': 'saudi arabia',
    'gremany': 'germany',
    'uaex': 'uae',
    'braizl': 'brazil',
    'usax': 'usa',
    'eygpt': 'egypt',
    'ngieria': 'nigeria'
}, inplace=True)

In [ ]:
df['City'] = df['City'].str.strip().str.lower()

In [ ]:
df['City'].replace(['?', '-', 'missing'], np.nan, inplace=True)

/tmp/ipykernel_11635/559083067.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].replace(['?', '-', 'missing'], np.nan, inplace=True)

In [ ]:
df['City'].unique()

array(['bursa', 'hai phong', 'cebu city', 'dammam', 'harar', 'nagoya',
       'islamabad', 'dire dawa', 'phuket', 'erdenet', 'mashhad',
       'seville', 'adelaide', 'fortaleza', 'puebla', 'mecca', 'bucharest',
       'hanoi', 'bandung', 'constanta', 'barranquilla', 'pretoria',
       'abu dhabi', 'trondheim', 'guadalajara', 'perth', 'dodoma',
       'tabriz', 'yangon', 'moscow', 'hamburg', 'kumasi',
       'ho chi minh city', 'riyadh', 'can tho', 'beijing', 'rawalpindi',
       'toronto', 'cairo', 'warsaw', 'chennai', 'lyon', 'aswan',
       'cape town', 'cordoba', 'rabat', 'gothenburg', 'arusha',
       'monterrey', 'malmo', 'buenos aires', 'choibalsan', 'lagos',
       'kyiv', 'brisbane', 'liverpool', 'kano', 'sharjah', 'mumbai',
       'sao paulo', 'yekaterinburg', 'sylhet', 'cartagena', 'barcelona',
       'bangalore', 'lviv', 'da nang', 'tamale', 'arequipa', 'cape coast',
       'los angeles', 'naypyidaw', 'glasgow', 'london', 'palermo',
       'mandalay', 'erbil', 'khon kaen', 'basra', 'melbourne',
       'quezon city', 'calgary', 'manila', 'mawlamyine', 'izmir', 'dhaka',
       'giza', 'alexandria', 'isfahan', 'rosario', 'mekelle', 'nakuru',
       'surabaya', 'toulouse', 'vancouver', 'rotterdam', 'manchester',
       'gondar', 'santiago', 'milan', 'gdansk', 'marrakech', 'valparaiso',
       'paris', 'mbeya', 'kazan', 'medina', 'khulna', 'cluj-napoca',
       'makassar', 'chengdu', 'mexico city', 'naples', 'bago', 'iasi',
       'ottawa', 'shanghai', 'new york', 'medellin', 'johannesburg',
       'karachi', 'vasteras', 'yokohama', 'baghdad', 'ulaanbaatar',
       'chittagong', 'lahore', 'stavanger', 'poznan', 'eindhoven',
       'krakow', 'timisoara', 'istanbul', 'eldoret', 'sydney', 'fez',
       'al ain', 'chiclayo', 'osaka', 'rio de janeiro', 'bilbao',
       'marseille', 'berlin', 'cologne', 'accra', 'oslo', 'jakarta',
       'salvador', 'montreal', 'rajshahi', 'casablanca', 'abuja', 'kyoto',
       'trujillo', 'valencia', 'adana', 'turin', 'bergen', 'uppsala',
       'durban', 'tokyo', 'dubai', 'tehran', 'kristiansand',
       'saint petersburg', 'lima', 'brasilia', 'pattaya', 'stockholm',
       'tijuana', 'kisumu', 'dar es salaam', 'delhi', 'houston', 'medan',
       'ankara', 'mwanza', 'nairobi', 'sekondi', 'mombasa', 'ajman',
       'davao', 'kolkata', 'tangier', 'amsterdam', 'jeddah',
       'port harcourt', 'novosibirsk', 'ibadan', 'zamboanga', 'luxor',
       'mosul', 'kharkiv', 'nice', 'wroclaw', 'cali', 'addis ababa',
       'concepcion', 'guangzhou', 'munich', 'antofagasta', 'faisalabad',
       'phoenix', 'madrid', 'rome', 'odessa', 'la plata', 'mendoza',
       'murun', 'chicago', 'kraaj', 'bangkok', 'karaj', 'frankfurt',
       'the hague', 'chiang mai', 'port elizabeth', 'temuco', 'shenzhen',
       'bogota', 'utrecht', 'birmingham', 'najaf', 'cusco', 'palemro',
       'dnipro', 'darkhan', 'unknown', 'bregen', 'adnaa', 'kristinasand',
       'cbeu city', 'teumco'], dtype=object)

In [ ]:
df['City'].replace({
    'kolktaa': 'kolkata',
    'vanocuver': 'vancouver',
    'mainla': 'manila',
    'madird': 'madrid',
    'marsielle': 'marseille',
    'yokhoama': 'yokohama',
    'sao pualo': 'sao paulo',
    'tamlae': 'tamale',
    'barsa': 'barcelona',
    'ngaoya': 'nagoya',
    'vatseras': 'vasteras',
    'al ian': 'al ain',
    'pzonan': 'poznan',
    'turjillo': 'trujillo',
    'antofagsata': 'antofagasta',
    'oaska': 'osaka',
    'niarobi': 'nairobi',
    'rwaalpindi': 'rawalpindi',
    'kmuasi': 'kumasi',
    'shnaghai': 'shanghai',
    'joahnnesburg': 'johannesburg',
    'brsailia': 'brasilia',
    'amstredam': 'amsterdam',
    'saint peterbsurg': 'saint petersburg',
    'buchraest': 'bucharest',
    'adids ababa': 'addis ababa'
}, inplace=True)

In [ ]:
df['Country'].unique()

array(['turkey', 'vietnam', 'philippines', 'saudi arabia', 'ethiopia',
       'japan', 'pakistan', 'thailand', 'mongolia', 'iran', 'spain',
       'australia', 'brazil', 'mexico', 'romania', 'indonesia',
       'colombia', 'south africa', 'uae', 'norway', 'tanzania', 'myanmar',
       'russia', 'germany', 'ghana', 'china', 'canada', 'egypt', 'poland',
       'india', 'france', 'argentina', 'morocco', 'sweden', 'nigeria',
       'ukraine', 'uk', 'bangladesh', 'peru', 'usa', 'italy', 'iraq',
       'kenya', 'netherlands', 'chile', nan], dtype=object)

In [ ]:
cols = [
    'AQI','PM2.5','PM10','Deforestation_Rate_%','Afforestation_Rate_%',
    'Vehicles_Increase_%','Industries_Increase_%','Env_Budget_Million_USD',
    'Population_Density_Per_SqKm','CO2_Emissions_MT',
    'Green_Space_Ratio_%','Avg_Life_Expectancy_Index'
]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:
# zero / negative values
for col in cols:
    df.loc[df[col] <= 0, col] = np.nan

In [ ]:
df.loc[(df['Year'] < 2000) | (df['Year'] > 2025), 'Year'] = np.nan

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(35000, 15)

In [ ]:
df.describe()

,Year,AQI,PM2.5,PM10,Deforestation_Rate_%,Afforestation_Rate_%,Vehicles_Increase_%,Industries_Increase_%,Env_Budget_Million_USD,Population_Density_Per_SqKm,CO2_Emissions_MT,Green_Space_Ratio_%,Avg_Life_Expectancy_Index
count,34918.000000,34759.000000,34781.000000,34756.000000,34781.000000,34794.000000,34797.000000,34778.000000,3.478600e+04,3.476800e+04,34786.000000,34786.000000,34796.000000
mean,2018.481671,282.307241,130.183821,234.865257,4.657686,3.559386,15.031696,11.063403,5.836637e+02,1.485208e+04,362.880505,62.468698,131.407568
std,2.898003,4977.731859,2024.928007,4176.359566,83.918992,57.829389,220.868750,172.035657,1.060482e+04,2.269492e+05,5677.595870,884.480000,1769.269060
min,2000.000000,0.015000,0.006180,0.012510,0.000080,0.000220,0.001110,0.000990,3.096000e-02,2.608900e-01,0.062750,0.010270,0.061360
25%,2016.000000,66.545000,35.600000,58.847500,0.910000,0.820000,4.920000,3.500000,1.092300e+02,4.057165e+03,116.792500,29.180000,73.400000
50%,2018.000000,122.370000,65.600000,108.145000,2.240000,1.490000,7.780000,5.620000,2.227250e+02,8.176475e+03,171.790000,34.940000,77.280000
75%,2021.000000,180.200000,100.500000,164.302500,3.680000,2.550000,12.520000,8.770000,3.914275e+02,1.212845e+04,231.310000,39.990000,81.450000
max,2025.000000,338650.000000,159500.000000,257470.000000,5260.000000,4560.000000,22660.000000,14050.000000,1.160040e+06,2.174710e+07,393110.000000,48470.000000,85690.000000

In [ ]:
for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df.loc[(df[col] < lower) | (df[col] > upper), col] = np.nan

In [ ]:
df.isnull().sum()

Country                          56
City                             59
Year                             82
AQI                             631
PM2.5                           934
PM10                            856
Deforestation_Rate_%            300
Afforestation_Rate_%            304
Vehicles_Increase_%             830
Industries_Increase_%          1167
Env_Budget_Million_USD         4201
Population_Density_Per_SqKm    2058
CO2_Emissions_MT                835
Green_Space_Ratio_%            1682
Avg_Life_Expectancy_Index       554
dtype: int64

In [ ]:
df = df.dropna(subset=['Country', 'City'])
df['Year'] = df['Year'].fillna(df['Year'].median())

In [ ]:
# COUNTRY-WISE (environment data)
country_cols = [
    'AQI', 'PM2.5', 'PM10',
    'CO2_Emissions_MT',
    'Green_Space_Ratio_%'
]

In [ ]:
for col in country_cols:
    df[col] = df.groupby('Country')[col].transform(
        lambda x: x.fillna(x.median())
    )

In [ ]:
# YEAR-WISE (growth / trend data)
year_cols = [
    'Vehicles_Increase_%',
    'Industries_Increase_%',
    'Env_Budget_Million_USD'
]

In [ ]:
for col in year_cols:
    df[col] = df.groupby('Year')[col].transform(
        lambda x: x.fillna(x.median())
    )

In [ ]:
# GLOBAL MEDIAN (remaining columns)
remaining_cols = [
    'Deforestation_Rate_%',
    'Afforestation_Rate_%',
    'Population_Density_Per_SqKm',
    'Avg_Life_Expectancy_Index'
]

In [ ]:
for col in remaining_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_11635/1937655.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 34885 entries, 0 to 36436
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      34885 non-null  object
 1   City                         34885 non-null  object
 2   Year                         34885 non-null  float64
 3   AQI                          34885 non-null  float64
 4   PM2.5                        34885 non-null  float64
 5   PM10                         34885 non-null  float64
 6   Deforestation_Rate_%         34885 non-null  float64
 7   Afforestation_Rate_%         34885 non-null  float64
 8   Vehicles_Increase_%          34885 non-null  float64
 9   Industries_Increase_%        34885 non-null  float64
 10  Env_Budget_Million_USD       34885 non-null  float64
 11  Population_Density_Per_SqKm  34885 non-null  float64
 12  CO2_Emissions_MT             34885 non-null  float64
 13  Green_Space_Ratio_%          34885 non-null  float64
 14  Avg_Life_Expectancy_Index    34885 non-null  float64
dtypes: float64(13), object(2)
memory usage: 4.3+ MB

Country                        0
City                           0
Year                           0
AQI                            0
PM2.5                          0
PM10                           0
Deforestation_Rate_%           0
Afforestation_Rate_%           0
Vehicles_Increase_%            0
Industries_Increase_%          0
Env_Budget_Million_USD         0
Population_Density_Per_SqKm    0
CO2_Emissions_MT               0
Green_Space_Ratio_%            0
Avg_Life_Expectancy_Index      0
dtype: int64

In [ ]:
df.groupby('Country')['AQI'].mean().sort_values(ascending=False).head(10)

Country
myanmar       262.665435
china         260.531461
bangladesh    259.482932
mongolia      259.477084
nigeria       258.998765
iran          257.812923
india         257.097725
iraq          257.091634
egypt         256.596228
pakistan      256.118460
Name: AQI, dtype: float64

In [ ]:
df["City"].unique()

array(['bursa', 'hai phong', 'cebu city', 'dammam', 'harar', 'nagoya',
       'islamabad', 'dire dawa', 'phuket', 'erdenet', 'mashhad',
       'seville', 'adelaide', 'fortaleza', 'puebla', 'mecca', 'bucharest',
       'hanoi', 'bandung', 'constanta', 'barranquilla', 'pretoria',
       'abu dhabi', 'trondheim', 'guadalajara', 'perth', 'dodoma',
       'tabriz', 'yangon', 'moscow', 'hamburg', 'kumasi',
       'ho chi minh city', 'riyadh', 'can tho', 'beijing', 'rawalpindi',
       'toronto', 'cairo', 'warsaw', 'chennai', 'lyon', 'aswan',
       'cape town', 'cordoba', 'rabat', 'gothenburg', 'arusha',
       'monterrey', 'malmo', 'buenos aires', 'choibalsan', 'lagos',
       'kyiv', 'brisbane', 'liverpool', 'kano', 'sharjah', 'mumbai',
       'sao paulo', 'yekaterinburg', 'sylhet', 'cartagena', 'barcelona',
       'bangalore', 'lviv', 'da nang', 'tamale', 'arequipa', 'cape coast',
       'los angeles', 'naypyidaw', 'glasgow', 'london', 'palermo',
       'mandalay', 'erbil', 'khon kaen', 'basra', 'melbourne',
       'quezon city', 'calgary', 'manila', 'mawlamyine', 'izmir', 'dhaka',
       'giza', 'alexandria', 'isfahan', 'rosario', 'mekelle', 'nakuru',
       'surabaya', 'toulouse', 'vancouver', 'rotterdam', 'manchester',
       'gondar', 'santiago', 'milan', 'gdansk', 'marrakech', 'valparaiso',
       'paris', 'mbeya', 'kazan', 'medina', 'khulna', 'cluj-napoca',
       'makassar', 'chengdu', 'mexico city', 'naples', 'bago', 'iasi',
       'ottawa', 'shanghai', 'new york', 'medellin', 'johannesburg',
       'karachi', 'vasteras', 'yokohama', 'baghdad', 'ulaanbaatar',
       'chittagong', 'lahore', 'stavanger', 'poznan', 'eindhoven',
       'krakow', 'timisoara', 'istanbul', 'eldoret', 'sydney', 'fez',
       'al ain', 'chiclayo', 'osaka', 'rio de janeiro', 'bilbao',
       'marseille', 'berlin', 'cologne', 'accra', 'oslo', 'jakarta',
       'salvador', 'montreal', 'rajshahi', 'casablanca', 'abuja', 'kyoto',
       'trujillo', 'valencia', 'adana', 'turin', 'bergen', 'uppsala',
       'durban', 'tokyo', 'dubai', 'tehran', 'kristiansand',
       'saint petersburg', 'lima', 'brasilia', 'pattaya', 'stockholm',
       'tijuana', 'kisumu', 'dar es salaam', 'delhi', 'houston', 'medan',
       'ankara', 'mwanza', 'nairobi', 'sekondi', 'mombasa', 'ajman',
       'davao', 'kolkata', 'tangier', 'amsterdam', 'jeddah',
       'port harcourt', 'novosibirsk', 'ibadan', 'zamboanga', 'luxor',
       'mosul', 'kharkiv', 'nice', 'wroclaw', 'cali', 'addis ababa',
       'concepcion', 'guangzhou', 'munich', 'antofagasta', 'faisalabad',
       'phoenix', 'madrid', 'rome', 'odessa', 'la plata', 'mendoza',
       'murun', 'chicago', 'kraaj', 'bangkok', 'karaj', 'frankfurt',
       'the hague', 'chiang mai', 'port elizabeth', 'temuco', 'shenzhen',
       'bogota', 'utrecht', 'birmingham', 'najaf', 'cusco', 'palemro',
       'dnipro', 'darkhan', 'unknown', 'bregen', 'adnaa', 'kristinasand',
       'cbeu city', 'teumco'], dtype=object)